### ISSUE TITLE
Add documentation on how to restrict namespace access

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#33]

**Comment by knelasevero** [comment]
Even though limiting namespace access with RBAC is good practice, now that we have the "controller" key in our CRD, we use it to make the relation between the created resources and which controller should act on it. The controller will watch all namespaces by default, but only act on the resources with the right "controller" key.

So restricting namespace access is not needed right now, even with multiple controllers and multiple contexts and namespaces.

Please restrict namespace access in prod, specially if this is a security guideline in your company :smile:  (if you are reading this here coming from a search result)! But since this is not needed to use the tool in a minimal environment, I will close the issue.
