### ISSUE TITLE
Start planning next milestone

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#87]
We're very close to milestone 0.1.0. This means that we need to list features for the next milestone.

**Comment by ckcks12** [comment]
Does this have a polling feature? like when I update the secret's value I hope the operator detects it. 

And also it seems to be nice to have a feature like putting a hash of secret CRD into the related deployment.
so that when the secret has been inserted or updated it lets the related deployment also be restarted.
(just like configmap generator)

**Comment by riccardomc** [comment]
Hi @ckcks12 , thanks for your interest! I believe they're both excellent suggestions.

Having a polling feature is definitely on our radar and there's an issue for that: https://github.com/ContainerSolutions/externalsecret-operator/issues/42

The second one seems a bit more involved, would you mind opening an issue and describing your proposal?
